name: Docker Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug environment variables
        run: |
          echo "AWS Region: us-east-1"
          echo "Docker image URL: 982081066879.dkr.ecr.us-east-1.amazonaws.com/mi-app-docker:latest"

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-logi
